name: huff
favicon: null
layout_spectrum: 0.21006
typography_spectrum: 0.04066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#404b5d'
    - '#96785e'
    - '#f6c8a4'
    - '#8eb8f4'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
