name: huff
favicon: null
layout_spectrum: 0.25702457851730287
typography_spectrum: 0.6089909067377448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4bfb9'
    - '#010d01'
    - '#a5a09d'
    - '#232b18'
    - '#58534f'
  brandStrength: 0.8125
  lightness: 0.48128580558113754
  saturation: 0.642884585307911
  rhythmicContrast: 0.5407479859422892
purpose: []
