name: huff
favicon: null
layout_spectrum: 0.21006
typography_spectrum: 0.6089909067377448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#004157'
    - '#595e58'
    - '#d5c091'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
